batch_size: 64
budget: 0.06394514269306989
clip_eps: 0.16669578694511536
cost_gamma: 0.9212486630711857
cost_lam: 0.9522199146802558
ent_coef: 0.031032932042185678
epochs: 7
gamma: 0.9587615364693198
hidden_dim: 256
lr: 0.0010360843856929214
max_kl: 0.011576319312774426
num_layers: 3
use_orthogonal_init: false
