batch_size: 32
budget: 0.20258628609558368
clip_eps: 0.18286856450348415
cost_gamma: 0.9083463455004739
cost_lam: 0.9793707896021834
ent_coef: 0.0009894243679250125
epochs: 10
gamma: 0.9960534712203585
hidden_dim: 512
lr: 0.00013487852956240443
nu_lr: 0.009244303191711047
num_layers: 2
use_orthogonal_init: false
