batch_size: 128
budget: 0.13808055327935376
clip_eps: 0.12329282382562871
cost_gamma: 0.9374855355430844
cost_lam: 0.9548399664856546
ent_coef: 0.02879828260100277
epochs: 6
gamma: 0.9769619974028786
hidden_dim: 512
lr: 0.0006063478814481848
nu_lr: 0.0065528519278888414
num_layers: 2
use_orthogonal_init: false
