batch_size: 128
budget: 0.40301146547543615
clip_eps: 0.2088669922159268
cost_gamma: 0.9814881299151924
cost_lam: 0.9249026205916313
ent_coef: 0.012370778345714768
epochs: 8
gamma: 0.9135556350413024
hidden_dim: 256
lr: 0.0005015190060086729
nu_lr: 0.0018742560027123782
num_layers: 4
use_orthogonal_init: false
