batch_size: 32
clip_eps: 0.15311534550117886
ent_coef: 0.026825548774657496
epochs: 9
gamma: 0.9082844983647367
hidden_dim: 256
lambda_penalty: 1.731666584210391
lr: 0.0003043993606488332
num_layers: 2
use_orthogonal_init: true
