batch_size: 128
clip_eps: 0.18942699379626968
ent_coef: 0.03255281678267504
epochs: 9
gamma: 0.9502022859225662
hidden_dim: 128
lambda_sem: 1.8623086292632862
lr: 0.0007473473928564832
num_layers: 4
use_orthogonal_init: true
