batch_size: 32
clip_eps: 0.10801530334872955
ent_coef: 0.032382638976291296
epochs: 7
gamma: 0.9518097984759165
hidden_dim: 256
lambda_sem: 0.7094709283886993
lr: 0.0010829195646573702
num_layers: 4
use_orthogonal_init: false
